Add API call "editMonitor"
ludeeus/pyuptimerobot pull request #18
Opened 2022-02-02 00:33 UTC by chemelli74

## Proposed change

Add API call "editMonitor"

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (which adds functionality)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Black (`make lint`)
- [x] Coverage is still 100% (check with `make coverage`)
- [ ] Tests have been added to verify that the new code works.

2022-02-02 05:44 UTC, ludeeus requested changes
This is missing tests.

2022-02-02 13:50 UTC, chemelli74 commented
> This is missing tests.

Tests added.

2022-02-20 18:40 UTC, ludeeus requested changes
This is missing tests

2022-02-20 18:40 UTC, ludeeus commented on pyuptimerobot/uptimerobot.py
> +    async def async_edit_monitor(self, **kwargs) -> UptimeRobotApiResponse:
This needs more work, the `id` argument is not optional.

2022-02-20 19:42 UTC, chemelli74 commented on pyuptimerobot/uptimerobot.py
> +    async def async_edit_monitor(self, **kwargs) -> UptimeRobotApiResponse:
Unfortunately I have not much experience with decorators :-(

2022-02-20 19:44 UTC, ludeeus commented on pyuptimerobot/uptimerobot.py
> +    async def async_edit_monitor(self, **kwargs) -> UptimeRobotApiResponse:
This is not about decorators, this is about the signature of the method.

2022-02-21 08:45 UTC, ludeeus requested changes

2022-02-21 08:45 UTC, ludeeus commented on pyuptimerobot/uptimerobot.py
> +        self, monitor_id: int, **kwargs
```suggestion
        self,
        id: int,
        **kwargs,
```
`monitor_id` and `id` is not the same

2022-02-22 12:50 UTC, merged