Fix pytest_asyncio warning
ludeeus/pyuptimerobot pull request #19
Opened 2022-02-02 13:32 UTC by chemelli74

## Proposed change

Running test you get a warning:
```
../../usr/local/python/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191
  /usr/local/python/lib/python3.10/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
```

This PR fix it.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionalit)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Black (`make lint`)
- [x] Coverage is still 100% (check with `make coverage`)
- [x] Tests have been added to verify that the new code works.

2022-02-02 14:00 UTC, ludeeus requested changes
Use https://python-poetry.org/docs/pyproject/ instead

2022-02-02 15:06 UTC, chemelli74 commented
> Use https://python-poetry.org/docs/pyproject/ instead

Done

2022-02-20 18:29 UTC, ludeeus requested changes

2022-02-20 18:29 UTC, ludeeus commented on pyproject.toml
> +asyncio_mode = "auto"
```suggestion
asyncio_mode = "strict"
```
This should be strict.

2022-02-20 19:20 UTC, ludeeus approved these changes

2022-02-20 19:26 UTC, merged